# Generated by Django 4.2.13 on 2024-06-24 12:45

from django.db import migrations, models
import reservationApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0003_alter_schedule_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='code',
            field=models.CharField(default=reservationApp.models.generate_unique_code, max_length=20, unique=True),
        ),
    ]
