# Generated by Django 4.2.13 on 2024-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0006_alter_booking_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
