# Generated by Django 4.2.13 on 2024-06-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0007_alter_bus_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Paid')], default='1', max_length=2),
        ),
    ]
